name: Build and deploy DefElement

on:
  workflow_call:
  workflow_dispatch:

permissions: {}

concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-website:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.14"
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Load Symfem cache
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: /home/runner/.cache/symfem
          key: symfem-cache
      - name: Load DefElement cache
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: .defelement-build-cache
          key: defelement-cache

      - name: Clone Symfem
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: ./symfem
          repository: mscroggs/symfem
          ref: main
          persist-credentials: false
      - name: Install Symfem
        run: |
            cd symfem
            python3 -m pip install .[optional]

      - name: Clone verification
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: ./verification
          repository: DefElement/DefElement
          ref: verification
          persist-credentials: false
        continue-on-error: true

      - run: mkdir -p ~/.local/share/fonts
        name: Make font folder
      - name: Clone Varela Round
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: ./varela-r
          repository: avrahamcornfeld/Varela-Round-Hebrew
          ref: master
          persist-credentials: false
      - run: cp varela-r/fonts/VarelaRound-Regular.otf ~/.local/share/fonts/
        name: Install Varela Round
      - name: Download and install Computer Modern
        run: |
          wget https://downloads.sourceforge.net/project/cm-unicode/cm-unicode/0.7.0/cm-unicode-0.7.0-otf.tar.xz
          tar -xf cm-unicode-0.7.0-otf.tar.xz
          cp cm-unicode-0.7.0/cmunti.otf ~/.local/share/fonts/

      - run: python3 -m pip install .
        name: Install defelement
      - run: python3 build.py _html --verification-json verification/verification.json --processes 4
        name: Build website HTML
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !github.event.pull_request.head.repo.fork }}
      - run: python3 build.py _html --verification-json verification/verification.json --processes 4
        name: Build website HTML
        if: ${{ github.event.pull_request.head.repo.fork }}

      - name: Setup Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0
        if: github.ref == 'refs/heads/main'
      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: '_html'
        if: github.ref == 'refs/heads/main'

      - name: Save Symfem cache
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: /home/runner/.cache/symfem
          key: symfem-cache-${{ github.run_id }}-${{ github.run_attempt }}
        if: github.ref == 'refs/heads/main'
      - name: Tidy DefElement cache
        run: python -c "from defelement.caching import tidy_cache; tidy_cache()"
        if: github.ref == 'refs/heads/main'
      - name: Save DefElement cache
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: .defelement-build-cache
          key: defelement-cache-${{ github.run_id }}-${{ github.run_attempt }}
        if: github.ref == 'refs/heads/main'
    permissions:
      contents: read

  deploy-website:
    name: Deploy
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'
    needs:
      - build-website
    permissions:
      contents: read
      pages: write # Allow updating of Github Pages website
      id-token: write # Needed by Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5.0.1
